In [2]:
#Dependencies
import requests
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import csv
import requests
import time

In [3]:
#bring in CSV
case_data = pd.read_csv("covid_confirmed_usafacts.csv")
case_data

,countyFIPS,County Name,State,StateFIPS,2020-01-22,2020-01-23,2020-01-24,2020-01-25,2020-01-26,2020-01-27,...,2021-07-06,2021-07-07,2021-07-08,2021-07-09,2021-07-10,2021-07-11,2021-07-12,2021-07-13,2021-07-14,2021-07-15
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,7262,7277,7277,7294,7299,7299,7306,7306,7320,7329
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,22043,22154,22154,22220,22267,22267,22337,22337,22464,22556
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,2347,2354,2354,2361,2365,2365,2367,2367,2373,2377
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,2693,2699,2699,2699,2702,2702,2704,2704,2708,2713
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,4801,4805,4820,4820,4833,4833,4853,4859,4869,4876
3189,56039,Teton County,WY,56,0,0,0,0,0,0,...,3804,3805,3807,3807,3816,3816,3824,3826,3831,3834
3190,56041,Uinta County,WY,56,0,0,0,0,0,0,...,2325,2327,2328,2328,2329,2329,2329,2330,2332,2333
3191,56043,Washakie County,WY,56,0,0,0,0,0,0,...,927,927,929,929,929,929,929,929,929,932
3192,56045,Weston County,WY,56,0,0,0,0,0,0,...,661,663,663,663,664,664,664,664,664,664

In [9]:
new_df = case_data[["County Name","State","2021-07-15"]]
new_df

                County Name State  2021-07-15
0     Statewide Unallocated    AL           0
1           Autauga County     AL        7329
2           Baldwin County     AL       22556
3           Barbour County     AL        2377
4              Bibb County     AL        2713
...                     ...   ...         ...
3188     Sweetwater County     WY        4876
3189          Teton County     WY        3834
3190          Uinta County     WY        2333
3191       Washakie County     WY         932
3192         Weston County     WY         664

[3193 rows x 3 columns]

In [19]:
#df = new_df.groupby('County Name').agg({'2021-07-15':'first'}).reset_index()
#df

# Filter the data so that only those sightings in the US are in a DataFrame
county_df = new_df.loc[new_df["State"] == "NJ", :]
county_df

                County Name State  2021-07-15
1804  Statewide Unallocated    NJ         829
1805       Atlantic County     NJ       31812
1806         Bergen County     NJ      105384
1807     Burlington County     NJ       44598
1808         Camden County     NJ       56208
1809       Cape May County     NJ        9318
1810     Cumberland County     NJ       17292
1811          Essex County     NJ       94829
1812     Gloucester County     NJ       30826
1813         Hudson County     NJ       88604
1814      Hunterdon County     NJ        9945
1815         Mercer County     NJ       34270
1816      Middlesex County     NJ       92933
1817       Monmouth County     NJ       76687
1818         Morris County     NJ       50596
1819          Ocean County     NJ       76893
1820        Passaic County     NJ       73638
1821          Salem County     NJ        6140
1822       Somerset County     NJ       30376
1823         Sussex County     NJ       14165
1824          Union County     NJ       72046
1825         Warren County     NJ       10071